export const CitiesArr = [
  {
    value: 'An Giang',
    slug: 'an-giang',
    type: 'tinh',
    label: 'An Giang',
    code: '89',
  },
  {
    value: 'Kon Tum',
    slug: 'kon-tum',
    type: 'tinh',
    label: 'Kon Tum',
    code: '62',
  },
  {
    value: 'Đắk Nông',
    slug: 'dak-nong',
    type: 'tinh',
    label: 'Đắk Nông',
    code: '67',
  },
  {
    value: 'Sóc Trăng',
    slug: 'soc-trang',
    type: 'tinh',
    label: 'Sóc Trăng',
    code: '94',
  },
  {
    value: 'Bình Phước',
    slug: 'binh-phuoc',
    type: 'tinh',
    label: 'Bình Phước',
    code: '70',
  },
  {
    value: 'Hưng Yên',
    slug: 'hung-yen',
    type: 'tinh',
    label: 'Hưng Yên',
    code: '33',
  },
  {
    value: 'Thanh Hóa',
    slug: 'thanh-hoa',
    type: 'tinh',
    label: 'Thanh Hóa',
    code: '38',
  },
  {
    value: 'Quảng Trị',
    slug: 'quang-tri',
    type: 'tinh',
    label: 'Quảng Trị',
    code: '45',
  },
  {
    value: 'Tuyên Quang',
    slug: 'tuyen-quang',
    type: 'tinh',
    label: 'Tuyên Quang',
    code: '08',
  },
  {
    value: 'Quảng Ngãi',
    slug: 'quang-ngai',
    type: 'tinh',
    label: 'Quảng Ngãi',
    code: '51',
  },
  {
    value: 'Hà Nội',
    slug: 'ha-noi',
    type: 'thanh-pho',
    label: 'Hà Nội',
    code: '01',
  },
  {
    value: 'Lào Cai',
    slug: 'lao-cai',
    type: 'tinh',
    label: 'Lào Cai',
    code: '10',
  },
  {
    value: 'Vĩnh Long',
    slug: 'vinh-long',
    type: 'tinh',
    label: 'Vĩnh Long',
    code: '86',
  },
  {
    value: 'Lâm Đồng',
    slug: 'lam-dong',
    type: 'tinh',
    label: 'Lâm Đồng',
    code: '68',
  },
  {
    value: 'Bình Định',
    slug: 'binh-dinh',
    type: 'tinh',
    label: 'Bình Định',
    code: '52',
  },
  {
    value: 'Nghệ An',
    slug: 'nghe-an',
    type: 'tinh',
    label: 'Nghệ An',
    code: '40',
  },
  {
    value: 'Kiên Giang',
    slug: 'kien-giang',
    type: 'tinh',
    label: 'Kiên Giang',
    code: '91',
  },
  {
    value: 'Hà Giang',
    slug: 'ha-giang',
    type: 'tinh',
    label: 'Hà Giang',
    code: '02',
  },
  {
    value: 'Phú Yên',
    slug: 'phu-yen',
    type: 'tinh',
    label: 'Phú Yên',
    code: '54',
  },
  {
    value: 'Lạng Sơn',
    slug: 'lang-son',
    type: 'tinh',
    label: 'Lạng Sơn',
    code: '20',
  },
  {
    value: 'Đà Nẵng',
    slug: 'da-nang',
    type: 'thanh-pho',
    label: 'Đà Nẵng',
    code: '48',
  },
  {
    value: 'Sơn La',
    slug: 'son-la',
    type: 'tinh',
    label: 'Sơn La',
    code: '14',
  },
  {
    value: 'Tây Ninh',
    slug: 'tay-ninh',
    type: 'tinh',
    label: 'Tây Ninh',
    code: '72',
  },
  {
    value: 'Nam Định',
    slug: 'nam-dinh',
    type: 'tinh',
    label: 'Nam Định',
    code: '36',
  },
  {
    value: 'Lai Châu',
    slug: 'lai-chau',
    type: 'tinh',
    label: 'Lai Châu',
    code: '12',
  },
  {
    value: 'Bến Tre',
    slug: 'ben-tre',
    type: 'tinh',
    label: 'Bến Tre',
    code: '83',
  },
  {
    value: 'Khánh Hòa',
    slug: 'khanh-hoa',
    type: 'tinh',
    label: 'Khánh Hòa',
    code: '56',
  },
  {
    value: 'Bình Thuận',
    slug: 'binh-thuan',
    type: 'tinh',
    label: 'Bình Thuận',
    code: '60',
  },
  {
    value: 'Cao Bằng',
    slug: 'cao-bang',
    type: 'tinh',
    label: 'Cao Bằng',
    code: '04',
  },
  {
    value: 'Hải Phòng',
    slug: 'hai-phong',
    type: 'thanh-pho',
    label: 'Hải Phòng',
    code: '31',
  },
  {
    value: 'Ninh Bình',
    slug: 'ninh-binh',
    type: 'tinh',
    label: 'Ninh Bình',
    code: '37',
  },
  {
    value: 'Yên Bái',
    slug: 'yen-bai',
    type: 'tinh',
    label: 'Yên Bái',
    code: '15',
  },
  {
    value: 'Gia Lai',
    slug: 'gia-lai',
    type: 'tinh',
    label: 'Gia Lai',
    code: '64',
  },
  {
    value: 'Hoà Bình',
    slug: 'hoa-binh',
    type: 'tinh',
    label: 'Hoà Bình',
    code: '17',
  },
  {
    value: 'Bà Rịa - Vũng Tàu',
    slug: 'ba-ria-vung-tau',
    type: 'tinh',
    label: 'Bà Rịa - Vũng Tàu',
    code: '77',
  },
  {
    value: 'Cà Mau',
    slug: 'ca-mau',
    type: 'tinh',
    label: 'Cà Mau',
    code: '96',
  },
  {
    value: 'Bình Dương',
    slug: 'binh-duong',
    type: 'tinh',
    label: 'Bình Dương',
    code: '74',
  },
  {
    value: 'Cần Thơ',
    slug: 'can-tho',
    type: 'thanh-pho',
    label: 'Cần Thơ',
    code: '92',
  },
  {
    value: 'Thừa Thiên Huế',
    slug: 'thua-thien-hue',
    type: 'tinh',
    label: 'Thừa Thiên Huế',
    code: '46',
  },
  {
    value: 'Đồng Nai',
    slug: 'dong-nai',
    type: 'tinh',
    label: 'Đồng Nai',
    code: '75',
  },
  {
    value: 'Tiền Giang',
    slug: 'tien-giang',
    type: 'tinh',
    label: 'Tiền Giang',
    code: '82',
  },
  {
    value: 'Điện Biên',
    slug: 'dien-bien',
    type: 'tinh',
    label: 'Điện Biên',
    code: '11',
  },
  {
    value: 'Vĩnh Phúc',
    slug: 'vinh-phuc',
    type: 'tinh',
    label: 'Vĩnh Phúc',
    code: '26',
  },
  {
    value: 'Quảng Nam',
    slug: 'quang-nam',
    type: 'tinh',
    label: 'Quảng Nam',
    code: '49',
  },
  {
    value: 'Đắk Lắk',
    slug: 'dak-lak',
    type: 'tinh',
    label: 'Đắk Lắk',
    code: '66',
  },
  {
    value: 'Thái Nguyên',
    slug: 'thai-nguyen',
    type: 'tinh',
    label: 'Thái Nguyên',
    code: '19',
  },
  {
    value: 'Hải Dương',
    slug: 'hai-duong',
    type: 'tinh',
    label: 'Hải Dương',
    code: '30',
  },
  {
    value: 'Bạc Liêu',
    slug: 'bac-lieu',
    type: 'tinh',
    label: 'Bạc Liêu',
    code: '95',
  },
  {
    value: 'Trà Vinh',
    slug: 'tra-vinh',
    type: 'tinh',
    label: 'Trà Vinh',
    code: '84',
  },
  {
    value: 'Thái Bình',
    slug: 'thai-binh',
    type: 'tinh',
    label: 'Thái Bình',
    code: '34',
  },
  {
    value: 'Hà Tĩnh',
    slug: 'ha-tinh',
    type: 'tinh',
    label: 'Hà Tĩnh',
    code: '42',
  },
  {
    value: 'Ninh Thuận',
    slug: 'ninh-thuan',
    type: 'tinh',
    label: 'Ninh Thuận',
    code: '58',
  },
  {
    value: 'Đồng Tháp',
    slug: 'dong-thap',
    type: 'tinh',
    label: 'Đồng Tháp',
    code: '87',
  },
  {
    value: 'Long An',
    slug: 'long-an',
    type: 'tinh',
    label: 'Long An',
    code: '80',
  },
  {
    value: 'Hậu Giang',
    slug: 'hau-giang',
    type: 'tinh',
    label: 'Hậu Giang',
    code: '93',
  },
  {
    value: 'Quảng Ninh',
    slug: 'quang-ninh',
    type: 'tinh',
    label: 'Quảng Ninh',
    code: '22',
  },
  {
    value: 'Phú Thọ',
    slug: 'phu-tho',
    type: 'tinh',
    label: 'Phú Thọ',
    code: '25',
  },
  {
    value: 'Quảng Bình',
    slug: 'quang-binh',
    type: 'tinh',
    label: 'Quảng Bình',
    code: '44',
  },
  {
    value: 'Hồ Chí Minh',
    slug: 'ho-chi-minh',
    type: 'thanh-pho',
    label: 'Hồ Chí Minh',
    code: '79',
  },
  {
    value: 'Hà Nam',
    slug: 'ha-nam',
    type: 'tinh',
    label: 'Hà Nam',
    code: '35',
  },
  {
    value: 'Bắc Ninh',
    slug: 'bac-ninh',
    type: 'tinh',
    label: 'Bắc Ninh',
    code: '27',
  },
  {
    value: 'Bắc Giang',
    slug: 'bac-giang',
    type: 'tinh',
    label: 'Bắc Giang',
    code: '24',
  },
  {
    value: 'Bắc Kạn',
    slug: 'bac-kan',
    type: 'tinh',
    label: 'Bắc Kạn',
    code: '06',
  },
];
